version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
        production-dependencies:
          dependency-type: "production"
        development-dependencies:
          dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  # Module: sagemaker-endpoint
  - package-ecosystem: "pip"
    directory: "modules/sagemaker/sagemaker-endpoint"
    schedule:
      interval: "weekly"
    groups:
        production-dependencies:
          dependency-type: "production"
        development-dependencies:
          dependency-type: "development"
