name: mlflow-fargate
path: git::https://github.com/awslabs/aiops-modules.git//modules/mlflow/mlflow-fargate?ref=release/1.5.0&depth=1
targetAccount: primary
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: VpcId
  - name: subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: PrivateSubnetIds
  - name: ecr-repository-name
    valueFrom:
      moduleMetadata:
        group: storage
        name: ecr-mlflow
        key: EcrRepositoryName
  - name: artifacts-bucket-name
    valueFrom:
      moduleMetadata:
        group: storage
        name: buckets
        key: ArtifactsBucketName
  - name: rds-hostname
    valueFrom:
      moduleMetadata:
        group: storage
        name: mlflow-mysql
        key: DatabaseHostname
  - name: rds-port
    valueFrom:
      moduleMetadata:
        group: storage
        name: mlflow-mysql
        key: DatabasePort
  - name: rds-credentials-secret-arn
    valueFrom:
      moduleMetadata:
        group: storage
        name: mlflow-mysql
        key: CredentialsSecretArn
  - name: rds-security-group-id
    valueFrom:
      moduleMetadata:
        group: storage
        name: mlflow-mysql
        key: SecurityGroupId
  - name: efs-removal-policy
    value: DESTROY
