name: fine-tuning-6B
forceDependencyRedeploy: True
toolchainRegion: us-east-1
groups:
  - name: base
    path: manifests/fine-tuning-6B/base-modules.yaml
  - name: images
    path: manifests/fine-tuning-6B/images-modules.yaml
  - name: core
    path: manifests/fine-tuning-6B/core-modules.yaml
  - name: integration
    path: manifests/fine-tuning-6B/integration-modules.yaml
  - name: ray-operator
    path: manifests/fine-tuning-6B/ray-operator-modules.yaml
  - name: ray-cluster
    path: manifests/fine-tuning-6B/ray-cluster-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    codebuildImage: aws/codebuild/standard:7.0
    parametersGlobal:
      rayNamespaceName: ray
      draImportPath: /ray/import/
      draExportPath: /ray/export/
    regionMappings:
      - region: us-east-1
        default: true
