# This is an example manifest group.
# Replace the parameters with the parameters for your model below prior the deployment.
name: endpoint
path: git::https://github.com/awslabs/aiops-modules.git//sagemaker/fmops/sagemaker-endpoint?ref=release/1.8.0&depth=1
parameters:
  - name: sagemaker_project_id
    value: project-1
  - name: sagemaker_project_name
    value: project-1
  - name: model_package_arn
    value: arn:aws:sagemaker:<region>:<account>:model-package/<package-name>/1
  - name: instance_type
    value: ml.m5.large
  - name: vpc_id
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: VpcId
  - name: subnet_ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: PrivateSubnetIds
  - name: sagemaker-domain-id
    valueFrom:
      moduleMetadata:
        group: sagemaker-studio
        name: studio
        key: StudioDomainId
  - name: sagemaker-domain-arn
    valueFrom:
      moduleMetadata:
        group: sagemaker-studio
        name: studio
        key: StudioDomainArn
  - name: managed_instance_scaling
    value: True
  - name: scaling_max_instance_count
    value: 10
