name: llm-rag
path: modules/examples/llm-rag
parameters:
  - name: cognito-pool-id
    value: ap-south-1_LtGUQv2Kx
  - name: os-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: storage
        name: opensearch
        key: OpenSearchDomainEndpoint