name: mlops-qna-rag
toolchainRegion: us-east-1
forceDependencyRedeploy: true
groups:
  - name: networking
    path: manifests/fmops-qna-rag/networking-modules.yaml
  - name: storage
    path: manifests/fmops-qna-rag/storage-modules.yaml
  - name: qna-rag
    path: manifests/fmops-qna-rag/qna-rag-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true