name: sagemaker-custom-kernel
path: git::https://github.com/awslabs/aiops-modules.git//modules/sagemaker/sagemaker-custom-kernel?ref=release/1.7.2&depth=1
targetAccount: dev
parameters:
  - name: ecr-repo-name
    valueFrom:
      moduleMetadata:
        group: storage
        name: ecr-sagemaker-kernel
        key: EcrRepositoryName
  - name: studio-domain-id
    valueFrom:
      moduleMetadata:
        group: sagemaker-studio
        name: studio
        key: StudioDomainId
  - name: studio-domain-name
    valueFrom:
      moduleMetadata:
        group: sagemaker-studio
        name: studio
        key: StudioDomainName
  - name: studio-execution-role-arn
    valueFrom:
      moduleMetadata:
        group: sagemaker-studio
        name: studio
        key: SageMakerExecutionRoleArn
  - name: sagemaker-image-name
    value: echo-kernel
  - name: app-image-config-name
    value: echo-kernel-app-config
  - name: custom-kernel-name
    value: echo
  - name: kernel-user-uid
    value: '0'
  - name: kernel-user-gid
    value: '0'
  - name: kernel-user-home-mount-path
    value: /root
