version: 0.2

phases:
  build:
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
      - cdk synth --no-lookups

artifacts:
  base-directory: "cdk.out"
  files: "**/*"