AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  ProjectName:
    Type: String
    Description: The name of the project
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  StudioExecutionRoleArn:
    Type: String
    Description: The name of the Sagemaker Studio IAM Role
  ECRRepoName:
    Type: String
    Description: The name of the ECR repository
  StudioDomainId:
    Type: String
    Description: The id of the SageMaker Studio Domain

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "sagemaker:AddTags"
              - "sagemaker:DescribeDomain"
              - "sagemaker:UpdateDomain"
            Resource:
              - !Sub "arn:${AWS::Partition}:sagemaker:${AWS::Region}:${AWS::AccountId}:domain/${StudioDomainId}"
          - Effect: Allow
            Action:
              - "iam:PassRole"
            Resource:
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ProjectName}-${DeploymentName}-${ModuleName}-image-role"
              - !Ref StudioExecutionRoleArn
          - Action:
              - "ecr:*LayerUpload"
              - "ecr:Batch*"
              - "ecr:Create*"
              - "ecr:Delete*"
              - "ecr:Describe*"
              - "ecr:Get*"
              - "ecr:List*"
              - "ecr:Put*"
              - "ecr:UploadLayerPart"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepoName}"
        Version: 2012-10-17
      PolicyName: "mlops-modulespecific-policy"
      Roles: [!Ref RoleName]
