name: ray-benchmark
path: modules/eks/ray-ml-benchmark-image
parameters:
  - name: ecr-repository-name
    valueFrom:
      moduleMetadata:
        group: base
        name: ecr-ray-ml-images
        key: EcrRepositoryName
  - name: ecr-repository-arn
    valueFrom:
      moduleMetadata:
        group: base
        name: ecr-ray-ml-images
        key: EcrRepositoryArn
  - name: base-image-name
    value: rayproject/ray-ml
