version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall . "awscli>1.20.30"

  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"
      - TAGS="[{\"Key\":\"sagemaker:project-name\", \"Value\":\"${SAGEMAKER_PROJECT_NAME}\"}, {\"Key\":\"sagemaker:project-id\", \"Value\":\"${SAGEMAKER_PROJECT_ID}\"}"
      - |
        if [ -n "${SAGEMAKER_DOMAIN_ID}" ]; then
          TAGS="$TAGS, {\"Key\":\"sagemaker:domain-id\", \"Value\":\"${SAGEMAKER_DOMAIN_ID}\"}"
        fi
      - |
        if [ -n "${SAGEMAKER_DOMAIN_ARN}" ]; then
          TAGS="$TAGS, {\"Key\":\"sagemaker:domain-arn\", \"Value\":\"${SAGEMAKER_DOMAIN_ARN}\"}"
        fi
      - TAGS="$TAGS]"
      - |
        run-pipeline --module-name ml_pipelines.training.pipeline \
          --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
          --tags "$TAGS" \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${ARTIFACT_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PROJECT_NAME_ID}\",\"model_package_group_name\":\"${MODEL_PACKAGE_GROUP_NAME}\",\"base_job_prefix\":\"${SAGEMAKER_PROJECT_NAME_ID}\", \"bucket_kms_id\":\"${ARTIFACT_BUCKET_KMS_ID}\"}"
      - echo "Create/Update of the SageMaker Pipeline and execution completed."
