AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Module specific IAM permissions

Parameters:
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role
  EksClusterName:
    Type: String
    Description: The name of the EKS Cluster

Resources:
  Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "iam:CreatePolicy"
            Resource:
              - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/*"
          - Effect: Allow
            Action:
              - "eks:Create*"
              - "eks:Update*"
              - "eks:Delete*"
              - "eks:List*"
              - "eks:Describe*"
            Resource:
              - !Sub "arn:${AWS::Partition}:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EksClusterName}"
              - !Sub "arn:${AWS::Partition}:eks:${AWS::Region}:${AWS::AccountId}:*/${EksClusterName}/*"
        Version: 2012-10-17
      PolicyName: "strands-module-policy"
      Roles: [!Ref RoleName]
